kyma-project/template-operator

- README.md
- Update the create module instructions to reflects the latest changes in the CLI.
https://github.com/kyma-project/cli/issues/1423
> Update create mod instructions

- README.md
> docs: minor improvements

- README.md
- template.yaml
remove stable & rapid
change descriptions of alpha,fast,regular
update tests and docs
> Chore update channels

- README.md
https://github.com/kyma-project/lifecycle-manager/issues/324
> indicate channel name has no restrictions

- config/default/kustomization.yaml
- config/manager/kustomization.yaml
> update controller image

- .idea/modules.xml
- config/manager/kustomization.yaml
- Update registry references from `eu.gcr.io/kyma-project` to `europe-docker.pkg.dev/kyma-project/prod`
- Delete ide settings folder
* https://github.com/kyma-project/lifecycle-manager/issues/523
> Update registry references

- Makefile
- api/v1alpha1/status.go
- config/crd/bases/operator.kyma-project.io_samplehelms.yaml
- config/crd/bases/operator.kyma-project.io_samples.yaml
- config/default/kustomization.yaml
- controllers/sample_controller_rendered_resources.go
- controllers/sample_local_helm_controller.go
- controllers/suite_test.go
- main.go
add warning state and make the final state configurable
Related issue: https://github.com/kyma-project/lifecycle-manager/issues/525
> add warning state

- sec-scanners-config.yaml
- Add `rc-tag `and `dev-branch` to sec-scanners-config yaml file
- Remove `whitesource/subprojects` from sec-scanners-config yaml file
https://github.com/kyma-project/cli/issues/1755
> Add new fields to the sec scanners config file

- CODEOWNERS
> chore: Add TWs to codeowners

- module-config.yaml
> fix: Set current version for template-operator

- sec-scanners-config.yaml
- removed in a previous PR but maybe we should keep it, like majority of other modules
> fix: Reintroduce rc-tag in sec-scanners-config

- sec-scanners-config.yaml
- Reintroduce dev-branch field in sec scanners config
> fix: Reintroduce dev-branch to sec scanner cfg

- .github/workflows/lint-golangci.yml
- Makefile
- Upgrade golangci/golangci-lint-action to v4.0.0
- Upgrade golangci-lint version used by make lint target to v1.56.2
- Upgrade golangci-lint version used by GHA lint workflow to v1.56.2
> chore: Bump golangci-lint make and action

- Dockerfile
- Makefile
- api/go.mod
- config/crd/bases/operator.kyma-project.io_manageds.yaml
- config/crd/bases/operator.kyma-project.io_samples.yaml
- go.mod
- golang upgrade for docker builder to 1.22.1
- also results in needing to upgrade kustomize to 5.3.0
- also results in needing to upgrade controller tools to 0.14
- use golang 1.22.1 in E2E (from go.mod)
- re-generate crds! results in different formatting in description fields
> chore: Version upgrades: go 1.22.1, kustomize: 5.3, controller tools: 0.14

- docs/README.md
- docs/e2e-test.md
related issue: https://github.com/kyma-project/lifecycle-manager/issues/304
> chore: Add e2e test docs

- Dockerfile
- Fix permissions in DockerFile in preparation for the migration to ADO 
https://github.com/orgs/kyma-project/projects/30/views/15?pane=issue&itemId=60682205
> fix: Add permissions in DockerFile

- .github/dependabot.yml
- Configure Dependabot PR for api module
> chore: Configure Dependabot for api module

- module-config.yaml
- sec-scanners-config.yaml
- Update version to 1.0.0 for sec scanners config and module config
Resolves #195
> chore: Update version to 1.0.0 for sec scanners config and module config

- api/go.mod
- go.mod
- bumps the golang version in go.mod to match the version in the Dockerfile
> chore: Align golang to 1.22.4

- README.md
Add deprecation note for the `customStateCheck` attribute:
https://github.com/kyma-project/lifecycle-manager/pull/1708
https://github.com/kyma-project/lifecycle-manager/issues/1616
> chore: Add deprecation note for customStateCheck

- .github/workflows/create-release.yml
- scripts/release/upload_assets.sh
related https://github.com/kyma-project/lifecycle-manager/issues/1811
> fix: Upload assets from github action

- .github/workflows/build-template-operator.yml
Make `build-template-operator` react by release tag (semver)
> chore: Make job support release by tag

- .github/workflows/build-image.yml
- .github/workflows/create-release.yml
> fix: Add dependencies

- Dockerfile
- go.mod
- Bump golang versions for build img layer and tests to latest 1.23.2
> chore: Bump golang version to 1.23.2

- .github/workflows/build-image.yml
- .github/workflows/create-release.yml
- ...
- ...
- ...
https://github.com/kyma-project/lifecycle-manager/issues/1943
> chore: Make build image accept multiple tags

- .github/workflows/lint-markdown-links.yml
- Update lint-markdown-links.yml to use supported version of the action
- https://github.com/kyma-project/community/blob/main/docs/contributing/assets/allowed_actions.json
> chore: Update lint-markdown-links version

- module-config.yaml
- module-release-meta.yaml
- sec-scanners-config.yaml
- Introduce module-release-meta to be used in E2E tests
https://github.com/kyma-project/lifecycle-manager/issues/1849
> feat: Introduce modulereleasemeta to be used in E2E tests

- .github/workflows/build-image.yml
> fix: Build image event name

- module-config.yaml
- Populate the new fields (icons, resources, repository, documentation and manager)
- Use URLs for defaultCR and manifest
> feat: Update ModuleConfig file with the required ModuleCatalog fields

- module-config.yaml
> chore: Fix moduleconfig rawManifest in resources

- api/go.mod
- api/go.sum
- Bump golang.org/x/net to v0.33.0
> chore(deps): Bump golang.org/x/net to v0.33.0

- Dockerfile
- api/go.mod
- go.mod
Bump golang version.
**Changes proposed in this pull request:**
- Dockerfile
- go.mod
#2214
> chore: Bump golang runtime version

- Dockerfile
- go.mod
- Bump used go version to latest v.1.23.6
> chore: Bump go version to 1.23.6

- sec-scanners-config.yaml
- Update sec scanners config for checkmarxone migration
Resolves https://github.com/kyma-project/lifecycle-manager/issues/2029
> chore: Update sec scanners config for checkmarxone migration

- sec-scanners-config.yaml
- Add "latest" Image Tag to BDBA Scan
> chore: Add "latest" Image Tag to BDBA Scan

- Dockerfile
- api/go.mod
- go.mod
- supersedes https://github.com/kyma-project/template-operator/pull/353
- ...
- ...
- ...
> chore: Bump golang from 1.24.1 to 1.24.2
